### PR TITLE
Miscellaneous improvements

### PR DESCRIPTION
**Pull request by TacoTheDank**
Hey.

### 1st commit
- Update gradle wrapper to 6.7.1 using git bash

### 2nd commit
- Update Android Studio 4.1.0 -> 4.1.1
- Drastic reorganization and clean up of libraries
- Removed unused libraries

Please advise about [this change](https://github.com/Docile-Alligator/Infinity-For-Reddit/commit/06ec3639216e16caa6def335b07f07adea56b7e2#diff-2ca01842b956af2372ec00333ad25f2ae66ff2e2976e91f8a68a00e0a58bf6f2L5), as this class was removed while removing unused parts of BigImageViewer (so fresco is no longer included)

Overall, this cleanup of libraries drops the APK size by 1.9 MB (13.0 MB -> 11.1 MB) (a 15% decrease!)

### 3rd commit
- Corrected usage of ViewPager2 implementations

### 4th commit
- Fix an ExoPlayer deprecation

### 5th commit
- Update AndroidX Browser 1.2.0 -> 1.3.0 ([changelog](https://developer.android.com/jetpack/androidx/releases/browser))
- Update AndroidX Room 2.2.5 -> 2.2.6 ([changelog](https://developer.android.com/jetpack/androidx/releases/room))
- We need to add OkHttp to dependencies (and 4.2.2 was the latest transitive used)
- Update Dagger 2.29.1 -> 2.30.1 ([changelog](https://github.com/google/dagger/releases))
- Update Bridge 1.2.1 -> 1.3.0 ([changelog](https://github.com/livefront/bridge/releases))
- Update glide-transformations 4.1.0 -> 4.3.0 ([changelog](https://github.com/wasabeef/glide-transformations/blob/main/CHANGELOG.md))
- Update BigImageViewer 1.6.5 -> 1.7.0 ([changelog](https://github.com/Piasy/BigImageViewer/releases)) (look at commits)
- Update Markwon 4.5.0 -> 4.6.0 ([changelog](https://github.com/noties/Markwon/blob/master/CHANGELOG.md))
- Update FlowLayout 1.3.0 -> 1.3.3 ([changelog](https://github.com/nex3z/FlowLayout/releases))
- Update FastScroll 1.1.2 -> 1.1.5 ([changelog](https://github.com/zhanghai/AndroidFastScroll/releases))

### 6th commit
- Use some Compat classes that do the version checks internally

### CODE REVIEW

**Comment by Docile-Alligator** [comment]
Wow! Thank you very much! But have you tested the Toro (video autoplay) library after updating ExoPlayer?

**Comment by TacoTheDank** [comment]
@Docile-Alligator I hadn't gotten the chance yet, I'll do that soon.

**Comment by TacoTheDank** [comment]
@Docile-Alligator The ExoPlayer update is no good :( gets crashes... I've reverted it.

**Comment by Docile-Alligator** [comment]
I think the map change in FetchSubredditData is ok. This part of the code is from a pull request (https://github.com/Docile-Alligator/Infinity-For-Reddit/pull/170).

**Comment by Docile-Alligator** [comment]
Thank you!

**Pull request merged**
