### PR TITLE
Exclude transitive dependency from Google services.

### PR DESCRIPTION
**Pull request by OHermesJunior**
Found in this dependency graph:

```
\--- im.ene.toro3:toro-ext-exoplayer:3.7.0.2010003
     \--- com.google.android.exoplayer:extension-ima:2.10.3
          \--- com.google.android.gms:play-services-ads-identifier:16.0.0
               \--- com.google.android.gms:play-services-basement:16.0.1
```

### CODE REVIEW

**Comment by OHermesJunior** [comment]
Relevant #87

**Comment by grravity** [comment]
@OHermesJunior Is this to remove GMS for F-Droid (as discussed in #87)?

**Comment by OHermesJunior** [comment]
Yes!

**Comment by grravity** [comment]
Very happy about this! Thank you!

**Comment by Docile-Alligator** [comment]
Thank you so much!

**Pull request merged**
