### PR TITLE
More fixes related to markdown rendering

### LINKED ISSUE #504: Some text looking like html tags are hidden
Ex this reddit post: https://www.tunemymusic.com/?share=iud4h20q2a3u

In the comments people are mentioning some HTML tags, but they don't appear in the application:

Ex:

In the app

Screenshot_20211022-221725_Infinity_1

On Reddit.com

Screenshot_20211022-221858_Firefox_1

### PR DESCRIPTION
**Pull request by scria1000**
~~Since Reddit markdown does not support inline html, I removed the markwon html plugin and added `MarkwonInlineParserPlugin` instead to disable Html parsing, which also~~ fixed #504

~~Is this ok?~~

### CODE REVIEW

**Comment by scria1000** [comment]
So it's not ok , it broke something

**Comment by scria1000** [comment]
The main goal of this PR was to prevent html tags from being consumed and in doing so, fixing #504. I managed to do that without breaking superscript rendering. The changes made are mostly repetitive. Is this PR ok? Can we merge this?

**Comment by Docile-Alligator** [comment]
Thank you very much!

**Pull request merged**
