### PR TITLE
Add authentication for subreddit searching

### PR DESCRIPTION
**Pull request by vlakreeh**
The current subreddit search method doesn't use any authentication so Reddit will hide any quarantined subs making them completely inaccessible unless someone links it.

### CODE REVIEW

**Comment by Wilker-a** [comment]
will this authentication be optional? i personally don't care for quarantined or private subs when searching, and i don't want my queries to be associated to my account like this.

**Comment by vlakreeh** [comment]
> will this authentication be optional? i personally don't care for quarantined or private subs when searching, and i don't want my queries to be associated to my account like this.

That's seems like a good idea, but I'm not much of an android developer. I don't think I'd be capable of implementing a UI toggle like that.

**Comment by Wilker-a** [comment]
i understand, i know almost nothing about the xml stuff and other stuff that Android has too.

it is easier to implement an overload function to be called later depending in a variable though. that sounds simple enough to implement the button later

**Comment by vlakreeh** [comment]
I did some experimenting and was able to manage to add an anonymous searches setting, but I'll wait for @Docile-Alligator to give some confirmation if they'd want this feature.

**Comment by Docile-Alligator** [comment]
I will merge it after this app is published on f-droid. Thank you.

**Pull request merged**
