### PR TITLE
Return early with the preview if not in Data Saving Mode

### LINKED ISSUE #202: Show first picture of gallery posts instead of last one
When seeing an post that has more than 2 pictures, the preview for it shows the last picture instead the first one. This messes up some posts since you are supposed to see the 1st. picture first.

### PR DESCRIPTION
**Pull request by scria1000**
Gallery preview was not showing the first item despite not being in Data Saving Mode, this PR fixes it.

sorry about the multiple commits, please squash and merge

Resolves #202

### CODE REVIEW

**Comment by scria1000** [comment]
https://github.com/Docile-Alligator/Infinity-For-Reddit/blob/3b365dfe5de4d129e2b3538d3b7c001544415b59/app/src/main/java/ml/docilealligator/infinityforreddit/post/ParsePost.java#L562

Is this intentional? If the goal is to get additional previews for size comparison in data saving mode, should it not prefer jpg over png?

Meaning:
`(previews.isEmpty()) && mimeType.contains("png") || mimeType.contains("jpg")`

**Comment by Docile-Alligator** [comment]
I don't think this can fix the problem in #202. Did you check it?
`preview.getPreviewWidth() * preview.getPreviewHeight() > 5_000_000` is to find a smaller preview to show in the post feed. Unless Reddit's JSON response puts different images in the preview array, returning early does not do anything.

**Comment by scria1000** [comment]
> I don't think this can fix the problem in #202. Did you check it? `preview.getPreviewWidth() * preview.getPreviewHeight() > 5_000_000` is to find a smaller preview to show in the post feed. Unless Reddit's JSON response puts different images in the preview array, returning early does not do anything.

It shouldn't try to find smaller preview if it's not in Data Saving Mode, unless your intention was for it to happen anyway.

This is the part where the multiple previews get introduced:
https://github.com/Docile-Alligator/Infinity-For-Reddit/blob/3b365dfe5de4d129e2b3538d3b7c001544415b59/app/src/main/java/ml/docilealligator/infinityforreddit/post/ParsePost.java#L562

As you can see multiple previews will be added even if preview.IsEmpty() is false.

I experienced this issue myself where the gallery preview wouldn't show the first image in preview.

**Comment by Docile-Alligator** [comment]
Thank you. This is probably a typo. I will fix this and no need to return early.

**Pull request closed without merging**
