### PR TITLE
Start utilizing view binding

### PR DESCRIPTION
**Pull request by TacoTheDank**
ButterKnife is deprecated and replaced with ViewBinding.

I started small.

ButterKnife usages in AccountPostsActivity, AccountSavedThingActivity, and CommentActivity have been converted to ViewBinding.

Let me know what you think.

### CODE REVIEW

**Comment by Wladefant** [comment]
Hey, @TacoTheDank thank for your contributions how can I contact you?

**Comment by TacoTheDank** [comment]
@Wladefant Hi, what would you like to contact me for, if you don't mind me asking?

**Comment by Wladefant** [comment]
@TacoTheDank You seem to be an experienced android and open source developer. Just wanted to ask, among other things, what are the best practices to build a community, develop open source code with multiple developers... 😊

**Comment by Docile-Alligator** [comment]
Thank you! That's very nice! I am just too lazy to migrate butter knife to view binding.

**Comment by TacoTheDank** [comment]
@Wladefant I guess I could be considered experienced lol. Everything just sorta fell into place for me, so it's kinda hard for me to explain, exactly. I think what helps is making the experience of contributing feel authentic and whatnot.

I found this article that may help (I agree with the points given): https://adevait.com/blog/workplace/build-open-source-community

There's also this other one that I think is good (it's pointed more towards enterprise, but many of the points still apply): https://www.forbes.com/sites/glennsolomon/2021/07/27/how-to-build-and-foster-a-great-developer-community-best-practices-from-the-experts/

**Comment by Wladefant** [comment]
@TacoTheDank Thank you, but would be nice to ask other questions or hear your opinion about some things we do or will do 😁 (and maybe not in a merged pull request 😅). Here is my discord: Wladefant #8299

**Pull request merged**
