### PR TITLE
Allow parallel installation of debug and release versions

### PR DESCRIPTION
**Pull request by sal0max**
...by adding '.debug' suffix to application id

### CODE REVIEW

**Comment by adamantike** [comment]
Without having experience with Android development, these changes allowed me to run the app without Android Studio asking for the main app installation to be removed from my device before running a custom build.

Could this be reviewed, to simplify future contributions to the project?

**Comment by Wladefant** [comment]
@adamantike Maybe

**Comment by adamantike** [comment]
@sal0max, there are a few other (new?) usages of `app:layoutManager=".customviews...` in the default branch, that will need to be replaced for the app not to crash.

**Comment by kvithayathil** [comment]
Nice! We could split it into product flavours and then have support for different assets for the launch logo in the future. I mentioned this in #1122 before I saw this thread

**Comment by Docile-Alligator** [comment]
Thank you!

**Pull request merged**
