### PR TITLE
Update gradle and dependencies

### PR DESCRIPTION
**Pull request by TacoTheDank**
### 1st commit
- Delete generated/unused files

### 2nd commit
- Update gradle wrapper to 6.3 using git bash

### 3rd commit (look through changelogs of updated dependencies to see if there's anything new you'd like to implement)
- Rearrange and group dependencies
- Split up big exoplayer into smaller dependencies
- Update `com.alexvasilkov:gesture-views` 2.5.2 -> 2.6.0 ([changelog](https://github.com/alexvasilkov/GestureViews/releases))
- Update `io.reactivex.rxjava2:rxjava` 2.2.14 -> 2.2.19 ([changelog](https://github.com/ReactiveX/RxJava/blob/2.x/CHANGES.md))
- Update `com.squareup.retrofit2` 2.6.2 -> 2.7.2 ([changelog](https://github.com/square/retrofit/blob/master/CHANGELOG.md))
- `jp.wasabeef:glide-transformations` 4.0.0 -> 4.1.0 ([changelog](https://github.com/wasabeef/glide-transformations/blob/master/CHANGELOG.md))
- `com.google.dagger` 2.25.2 -> 2.27 ([changelog](https://github.com/google/dagger/releases))
- Butterknife 10.2.0 -> 10.2.1 ([changelog](https://github.com/JakeWharton/butterknife/blob/master/CHANGELOG.md))
- `com.github.santalu:aspect-ratio-imageview` 1.0.6 -> 1.0.9 ([read through the commits](https://github.com/santalu/aspect-ratio-imageview/commits/master)) (I hate when people don't provide changelogs)
- `com.github.Ferfalk:SimpleSearchView` 0.1.4 -> 0.1.5 ([read the commits since 0.1.4](https://github.com/Ferfalk/SimpleSearchView/releases))
- `org.greenrobot:eventbus` 3.1.1 -> 3.2.0 ([changelog](https://greenrobot.org/eventbus/changelog/))
- `com.libRG:customtextview` 2.2 -> 2.4 (2.2 to 2.3 [changes](https://user-images.githubusercontent.com/32376686/80008247-7c61d000-8495-11ea-8a77-b475ffcdd432.png), 2.3 to 2.4 [changes](https://user-images.githubusercontent.com/32376686/80007916-f34a9900-8494-11ea-974b-5577c3561d33.png))
- `com.github.livefront:bridge` 1.2.0 -> 1.2.1 ([changelog](https://github.com/livefront/bridge/releases))
- Update Android Studio 3.5.3 -> 3.6.3 ([changelog](https://developer.android.com/studio/releases))

### CODE REVIEW

**Comment by Docile-Alligator** [comment]
Thank you. But could you explain what you did on your third commit? Because I am not very familiar with git. Also, I tried updating Gradle but it made the whole project not compile and I found that it was due to the library com.github.Ferfalk:SimpleSearchView.

**Comment by TacoTheDank** [comment]
I just updated a bunch of dependencies.

Also, with the SimpleSearchView, I also got that error when I updated it to 0.1.5, so I downgraded back to 0.1.4 and rebuilt. But for some reason that recompile also failed, I think because of the same library (which shouldn't happen when reverting the version back to the original), so I thought that maybe something else was was interfering with the building process and kept the version update.

From what I remember, the errors are likely due to either the change to attrs at the end of [this](https://github.com/Ferfalk/SimpleSearchView/commit/c74eac9a48abf52f9ac6a204d742362a353d386a) commit, or the changes in [this](https://github.com/Ferfalk/SimpleSearchView/commit/6005691f3b1f111d70e7b5e3b2e0666d2e5936af) commit. You'll have to make little changes related to those commits. I can also just change the version back if you wish.

**Comment by Docile-Alligator** [comment]
Thank you. But why deleting many project files such as Project_Default.xml, some Test classes, etc? And could you explain the reason why you make so many changes in gradlew? Will the changes cause some unexpected effects in the future?

**Comment by TacoTheDank** [comment]
@Docile-Alligator The gradlew changes are made by the wrapper itself. They're updated automatically when updating the gradle wrapper using git bash. gradlew is actually just short for gradlew wrapper ([more or less](https://stackoverflow.com/questions/39627231/difference-between-using-gradlew-and-gradle)). They shouldn't cause any issues.

The .idea files are automatically generated, and thus aren't needed in the repo. Plus, they tend to make commits harder to read and dirty them up.

The tests I deleted aren't actually *doing* anything related to the code, they're basically just sample tests, so for all intents and purposes aren't needed either.

**Comment by Docile-Alligator** [comment]
Thank you very much for this!

**Pull request merged**
