### PR TITLE
Enable minify, reduce release apk size.

### PR DESCRIPTION
**Pull request by OHermesJunior**
This pull request enables minify (R8 and Proguard), reducing release apk file size, methods and classes, single dex file (as it has 64k methods limit), and optimize the code, improving performance.

Full diff:
infinity_minify

I don't know why it wasn't enabled before, but from my tests I don't see any regression.

### CODE REVIEW

**Comment by OHermesJunior** [comment]
This can be further improved by putting
```java
debuggable false
jniDebuggable false
```
And the increase in weight in "BUNDLE-METADATA" is caused by a mapping file generated by proguard, it's important to save that file in releases so you can trace the exceptions, but can probably be removed from the apk.

**Comment by Docile-Alligator** [comment]
Thank you! Great! The reason why I haven't enabled it is because I think I have to manually check for every library to get it's proguard rule.

**Comment by Docile-Alligator** [comment]
I will check that later. Thank you.

**Comment by OHermesJunior** [comment]
If the library has a proguard file, it will be used automatically. The only risks would be any regression caused by the app itself, or a library needing some rules but not having it (which is rare).

**Comment by Docile-Alligator** [comment]
That's cool. Thank you for your explanation.

**Pull request merged**
